---
title: "Annual mileage distribution plots EUR"
author: "Johanna Hoppe"
date: "2025-02-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)#
library(ggplot2)
library(data.table)
library(RColorBrewer)
#Insert pth to mileage data
AMdataPath <- "C:/Users/johannah/Documents/Paper/TCO/ISI driving profiles/export_veh_km.csv"
# Get the directory of the currently running script or Rmd
folder_path <- dirname(this.path::this.dir())
```

```{r}

# Apply mileage data on TCO (using bins to split mileage data)
# Calculate TCOgap compared to Diesel-mix for each bin
# Prepare data for plotting

# Sort AM data
AMdata <- fread(file = AMdataPath, header = TRUE, sep = ",", dec=".")
AMdata[, V1 := NULL]
AMdata[, period := substr(vehicleid, 1, 4)]
AMdata[, avkt := as.numeric(avkt)]
setnames(AMdata, "GKtype", "Vehicle Size")
AMdata[`Vehicle Size` == "tractor-trailer", `Vehicle Size` := "Tractor-Trailer"]
AMdata[`Vehicle Size` == "rigid", `Vehicle Size` := "Rigid"]
setnames(AMdata, "country", "Country")

AMdata <- AMdata[!`Vehicle Size` == "other"]
# Split AM data into equally sized bins
# Define global bin breaks based on the entire dataset
global_breaks <- seq(min(AMdata$avkt, na.rm = TRUE), max(AMdata$avkt, na.rm = TRUE), length.out = 201)

# Apply the same breaks to all groups
AMdata[, avkt_binned := cut(avkt, breaks = global_breaks, include.lowest = TRUE)]
# Calculate mean annual mileage for each bin
AMdata[, binMean := mean(avkt), by = c("avkt_binned", "Vehicle Size", "Country")]
# Calculate total yearly road km for each bin 
AMdata <- AMdata[, .(totRoadkm = sum(avkt)), by = c("Country", "Vehicle Size", "avkt_binned", "binMean")]
# Calculate total road km for EUR
AMdata[, totRoadkmEUR := sum(totRoadkm)]
# Calculate share of each bin in the total yearly road km in EUR 
AMdata[, shareKmEUR := totRoadkm/totRoadkmEUR]
```

```{r}
#TCO_plotting <- fread(file.path(folder_path, "calcTCOData", "3_ScenarioSpecificTCOdataFlexAM", "TCO_ACEAscen.csv"))
TCO_plotting <- fread(file.path(folder_path, "calcTCOData", "3_ScenarioSpecificTCOdataFlexAM", "TCO_ACEAscen_removePoliciesCase.csv"))
groupParameters <- FALSE
source(file.path(folder_path, "Plotting scripts", "PrepareTCOdataForPlotting.R"))
TCO_plotting <- TCO_plotting[, .(value = sum(value)), by = c("Country", "Vehicle Size", "Fuel Type", "ACEAscen", "Unit", "period")]

#OPEX and CAPEX still separated
TCOdrivingProfiles <- merge(TCO_plotting, AMdata, by = c("Country", "Vehicle Size"), allow.cartesian = TRUE)
TCOdrivingProfiles[Unit == "EUR/veh yr", value := value/binMean]
TCOdrivingProfiles[Unit == "EUR/veh yr", Unit := "EUR/km"]
#Sum up after unifying the unit
TCOdrivingProfiles <- TCOdrivingProfiles[, .(value = sum(value)), by = c("Country", "Vehicle Size", "Fuel Type", "ACEAscen", "Unit", "period", "avkt_binned", "shareKmEUR", "binMean")]

# Calculate TCO gap compared to Diesel Mix
DieselMix <- TCOdrivingProfiles[`Fuel Type` == "Diesel Mix"]
setnames(DieselMix, "value", "totDieselMix")
DieselMix <- unique(DieselMix[, c("Country", "Vehicle Size", "ACEAscen", "period", "totDieselMix", "avkt_binned")])

TCOdrivingProfiles <- TCOdrivingProfiles[!`Fuel Type` %in% c("Gas ICE", "Diesel Fossil", 
                                                             "Diesel Syn", "Diesel Bio", "Diesel Mix")]
TCOdrivingProfiles <- merge(TCOdrivingProfiles, DieselMix, by = c("Country", "Vehicle Size", "ACEAscen", "avkt_binned", "period"))
TCOdrivingProfiles[, TCOgap := value - totDieselMix][, totDieselMix := NULL]

#Selecting the edge Scenarios
TCOdrivingProfiles <- TCOdrivingProfiles[`Fuel Type` == "CH2 FCET" & ACEAscen %in% c("TechnologyAdvancesXH2a",
                                                                                     "TechnologyAdvancesXCNF",
                                                                                     "MediumAll") |
                                           `Fuel Type` == "LH2 FCET" & ACEAscen %in% c("TechnologyAdvancesXH2a",
                                                                                       "TechnologyAdvancesXCNF",
                                                                                       "MediumAll") |
                                           `Fuel Type` == "BET Mid" & ACEAscen %in% c("TechnologyAdvancesXELEa",
                                                                                      "TechnologyAdvancesXCNF",
                                                                                      "MediumAll") |
                                           `Fuel Type` == "BET Long" & ACEAscen %in% c("TechnologyAdvancesXELEa",
                                                                                       "TechnologyAdvancesXCNF",
                                                                                       "MediumAll")]

#Renaming scenarios
TCOdrivingProfiles[`Fuel Type` %in%  c("CH2 FCET", "LH2 FCET") & ACEAscen == "TechnologyAdvancesXH2a", ACEAscen := "Sensitivity Low"]
TCOdrivingProfiles[`Fuel Type` %in%  c("CH2 FCET", "LH2 FCET") & ACEAscen == "TechnologyBottlenecksXH2b", ACEAscen := "Sensitivity High"]

TCOdrivingProfiles[`Fuel Type` %in%  c("BET Mid", "BET Long") & ACEAscen == "TechnologyAdvancesXELEa", ACEAscen := "Sensitivity Low"]
TCOdrivingProfiles[`Fuel Type` %in%  c("BET Mid", "BET Long") & ACEAscen == "TechnologyBottlenecksXELEb", ACEAscen := "Sensitivity High"]


setorder(TCOdrivingProfiles, "Fuel Type", "ACEAscen", "period", "TCOgap")

TCOdrivingProfiles[, share := cumsum(shareKmEUR)*100, by = c("Fuel Type", "ACEAscen", "period")]

```

```{r, fig.width=14, fig.height=5, fig.fullwidth=FALSE}
yr <- c(2030, 2040)
trucktechs <- c("BET Long", "BET Mid", "CH2 FCET")
data <- copy(TCOdrivingProfiles)[period %in% yr & `Fuel Type` %in% trucktechs]
commonShares <- seq(0, 100, by = 0.01)  # Define a common range of shares


# Function to apply LOESS smoothing per Technology & Scenario
smooth_interpolation <- function(df) {
  fit <- loess(TCOgap ~ share, data = df, spar = 0.7)  # Adjust span for smoothness
  data.table(share = commonShares, TCOgap = predict(fit, newdata = commonShares))
}

# Apply smoothing to all groups
data <- data[, smooth_interpolation(.SD), by = .(`Fuel Type`, period, ACEAscen)]

ymax <- 1
ymin <- -0.5

data[!ACEAscen == "MediumAll" & TCOgap > 1, TCOgap := ymax]
data[!ACEAscen == "MediumAll" & TCOgap < -0.5, TCOgap := ymin]

# Reshape data for plotting
wideData <- dcast(data, `Fuel Type` + share +  period ~ ACEAscen, value.var = "TCOgap")

# Plot with ribbon shading for sensitivity
ggplot(wideData, aes(x = share, color = `Fuel Type`)) +
  geom_ribbon(aes(ymin = `Sensitivity High`, ymax = `Sensitivity Low`, fill = `Fuel Type`, color = NULL), alpha = 0.2) +
  geom_line(aes(y = MediumAll), size = 1) +
   facet_wrap(~ period) +
  geom_segment(aes(x = 0, xend = 100, y = 0, yend = 0), color = "darkgrey", size = 0.8, linetype = "dashed") +
  #geom_hline(yintercept = 0, color = "darkgrey", size = 0.8, linetype = "dashed") +  # Add a black line at y = 0
  theme_minimal() +
  labs(x = "Share", y = "TCO gap", title = paste("TCO gap over share of road kilometers for different technologies\nWithout policy support")) +
  scale_color_manual(values = c("#6497b1", "#d16b6b", "#88b04b", "#a17ea5")) +
  scale_fill_manual(values = c("#6497b1", "#d16b6b", "#88b04b", "#a17ea5")) +
  scale_y_continuous(limits = c(ymin, ymax))+
  scale_x_continuous(limits = c(0, 100))+
   theme(
    text = element_text(size = 14),  # General text size
    axis.title = element_text(size = 14),  # Axis title size
    axis.text = element_text(size = 14, color = "black"),  # Axis labels size
    # Adjust facet labels size
    strip.text = element_text(size = 14),
    
    # Adjust legend text size
    legend.key.size = unit(0.7, "cm"),  # Legend key size
    legend.text = element_text(size = 10),  # Legend text size
    legend.title = element_blank()  # Legend title size
  )

```







