---
title: "Truck Sales Prices"
date: "`r format(Sys.Date())`"
output:
  pdf_document:
    toc: yes
    number_sections: yes
    toc_depth: 4
    keep_tex: false
    template: cs2_latex_template.tex
    includes: 
      in_header: cs_pdf_header_include.tex
  html_document:
    toc: yes
    toc_float: yes
    toc_depth: 4
    number_sections: yes
geometry: "a4paper,landscape,left = 0.5cm,right = 0.5cm,top = 0.5cm,bottom = 0.5cm,footnotesep=0.0cm,footskip = 0.1cm"
subparagraph: yes
---

```{r , include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  error = TRUE,
  message = FALSE,
  fig.width = 5, 
  fig.height = 20)
# Get the directory of the currently running script or Rmd
folder_path <- dirname(this.path::this.dir())
```

```{r , include=FALSE}
library(data.table)
library(readxl)
library(ggplot2)
library(tibble)
```

```{r , include=FALSE}
Pathtofile <- file.path(folder_path, "calcTCOData", "3_ScenarioSpecificTCOdataFlexAM", "salesPrice_ACEAscen.csv")

SalesPrice <- fread(Pathtofile)

SalesPriceplotting <- copy(SalesPrice)
plotData <- copy(SalesPriceplotting)

groupParameters <- TRUE
source(file.path(folder_path, "Plotting scripts", "PrepareTCOdataForPlotting.R"))

tribble(
      ~Electricity,                      ~Hydrogen,         ~CNFfuels,       ~medium,
      "TechnologyAdvancesXELEa",          "Mix1",                    FALSE,      "default",
      
    )

```

```{r , include=TRUE}
VehCostScen <- "opt"
plotSalesPrice <- function(data, color_mapping) {
  p <- ggplot(data, aes(fill=Parameter, y=value, x=`Fuel Type`)) +
    geom_bar(position="stack", stat="identity", width = 0.8) +
    facet_wrap(`ACEAscen` ~ period, nrow = 5, ncol = 3) +
    theme(text = element_text(size = textSize)) +
    labs(x = "", y = "Truck (>12t) Sales Prices [EUR]", title = paste0(unique(data$Operation), " ", unique(data$`Vehicle Size`))) +
    scale_x_discrete(labels=function(x){sub("\\s", "\n", x)}) +
    theme(panel.grid.major=element_line(colour='#adadad'), panel.grid.minor=element_line(colour='#adadad')) + 
    scale_fill_manual(values=color_mapping)
  
  plot(p)
}

```

## Germany
#### Tractor-Trailer
```{r , include=TRUE}
yrs <- c(2050)
VehSize <- "Rigid"
Countr <- "DE"
trucktechs <- c("BET Long")
plotData <- plotData[`Vehicle Size` == VehSize & Country == Countr & period %in% yrs & `Fuel Type` %in% trucktechs]
plotSalesPrice(plotData, color_mapping)
```



