---
title: "supplementaryPlots"
author: "Johanna Hoppe"
date: "2025-05-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)#
library(ggplot2)
library(data.table)
library(RColorBrewer)
library(ggtext)
library(ggh4x)
library(ggforce)
library(patchwork)
library(scales)
library(colorspace)
library(viridisLite)
library(cowplot)
library(funkyheatmap)
library(stringr)
library(grid)
library(tibble)
library(ggpattern)

rm(list=ls())
mainFolder <- dirname(this.path::this.dir())
dataFolder <-  file.path(mainFolder, "data")
plotFolder <- file.path(mainFolder, "plots", "supplementary")
source(file.path(mainFolder, "Plotting scripts", "functions.R"))
source(file.path(mainFolder, "Plotting scripts", "plotFunctions.R"))
source(file.path(mainFolder, "Plotting scripts", "plotSettings.R"))

annualMileage <- data.table(truckClass = c("Rigid", "Rigid", "Rigid", "Tractor-trailer", "Tractor-trailer", "Tractor-trailer"),
                            operation = c("Urban", "Regional", "Long-haul", "Urban", "Regional", "Long-haul"),
                            am = c(30000, 85000, 140000, 40000, 90000, 160000))

DCOscenarios <- tribble(
  ~truckTech,         ~truckTCOscenario, ~counterTech, ~counterTechTCOscenario, ~DCOscenario,
  "BET small battery", "LC_HTMxPROG",    "ICET",       "HC_LTMxBAU",            "Optimistic",
  "BET large battery", "LC_HTMxPROG",    "ICET",       "HC_LTMxBAU",            "Optimistic",
  "FCET",              "LC_HTMxPROG",    "ICET",       "HC_LTMxBAU",            "Optimistic",
  "BET small battery", "MC_MTMxBAU",     "ICET",       "MC_MTMxBAU",            "Medium",
  "BET large battery", "MC_MTMxBAU",     "ICET",       "MC_MTMxBAU",            "Medium",
  "FCET",              "MC_MTMxBAU",     "ICET",       "MC_MTMxBAU",            "Medium",
  "BET small battery", "HC_LTMxBAU",     "ICET",       "LC_HTMxPROG",           "Pessimistic",
  "BET large battery", "HC_LTMxBAU",     "ICET",       "LC_HTMxPROG",           "Pessimistic",
  "FCET",              "HC_LTMxBAU",     "ICET",       "LC_HTMxPROG",           "Pessimistic"
)
setDT(DCOscenarios)


```

# Suppplementary Fig: BET vs FCET TCO x Annual mileage distribution bar plot 
```{r, fig.width= 5, fig.height= 8.5, fig.fullwidth=FALSE}
yr <- c(2030)
paperScenario <- "Current policies"
BETvsFCETdcoScenarios <- tribble(
  ~truckTech,         ~truckTCOscenario, ~counterTech, ~counterTechTCOscenario, ~DCOscenario,
  "BET small battery", "LC_HTMxPROG",    "FCET",       "HC_LTMxBAU",            "Optimistic",
  "BET large battery", "LC_HTMxPROG",    "FCET",       "HC_LTMxBAU",            "Optimistic",
  "BET small battery", "MC_MTMxBAU",     "FCET",       "MC_MTMxBAU",            "Medium",
  "BET large battery", "MC_MTMxBAU",     "FCET",       "MC_MTMxBAU",            "Medium",
  "BET small battery", "HC_LTMxBAU",     "FCET",       "LC_HTMxPROG",           "Pessimistic",
  "BET large battery", "HC_LTMxBAU",     "FCET",       "LC_HTMxPROG",           "Pessimistic"
)
setDT(BETvsFCETdcoScenarios)

TCOdata <- loadTCO(dataFolder)
mileageDistribution <- prepareMileageData(dataFolder)
DCOdata <- getDCO(BETvsFCETdcoScenarios, TCOdata)
setnames(mileageDistribution, "binMean", "annualM")
DCOmilageDistribution <- applyMileage(mileageDistribution, DCOdata)
DCOmilageDistributionShares <- calculateFreightActivityShares(DCOmilageDistribution, focus = "EUR")
TCOxAnnualMileage <- amDistributionBarPlot(DCOmilageDistributionShares, yr, paperScenario)

MetaTCOxAnnualMileage <- metaPlot(DCOmilageDistributionShares, paperScenario)

```

# Combine meta and mileage dstribution plot
```{r, fig.width=4.5, fig.height=5.5, fig.fullwidth=FALSE}
legend <- get_legend(
  TCOxAnnualMileage +
    theme(
      legend.position = "bottom",
      legend.justification = "left",   # start from left in its own box
      legend.box.just = "left"
    )
)

# 2. Remove legends from the plots
TCOxAnnualMileagePlot_noleg <- TCOxAnnualMileage + theme(legend.position = "none")
metaPlot_noleg <- MetaTCOxAnnualMileage + theme(legend.position = "none")

# 3. Combine the plots side by side
combined <- plot_grid(
  TCOxAnnualMileagePlot_noleg,
  metaPlot_noleg,
  ncol = 2,
  rel_widths = c(1.2, 0.8),
  align = "v",
  labels = c("a", "b"),
  label_size = baseTextSize,
  label_fontface = "bold",
  label_x = 0.02,
  label_y = 1.02,
  hjust = 0, vjust = 1
) +
  theme(plot.margin = margin(t = 10, r = 5, b = 5, l = 15))

# 4. Shift legend slightly to the right using a spacer
legend_shifted <- plot_grid(
  NULL,      # empty spacer
  legend,
  ncol = 2,
  rel_widths = c(0.05, 0.3)  # First number: empty space on the left.Second number:space the legend occupies.
)

# 5. Combine plots and shifted legend vertically
finalPlot <- plot_grid(
  combined,
  legend_shifted,
  ncol = 1,
  rel_heights = c(1, 0.1)  
)
finalPlot_with_labels <- ggdraw(finalPlot) +
  draw_label(
    "Optimistic", x = 0.02, y = 0.775, angle = 90,
    fontface = "bold",
    fontfamily = "sans",
    size = baseTextSize * 1.2,
    hjust = 0
  ) +
  draw_label(
    "Medium", x = 0.02, y = 0.525, angle = 90,
    fontface = "bold",
    fontfamily = "sans",
    size = baseTextSize * 1.2,
    hjust = 0
  ) +
  draw_label(
    "Pessimistic", x = 0.02, y = 0.235, angle = 90,
    fontface = "bold",
    fontfamily = "sans",
    size = baseTextSize * 1.2,
    hjust = 0
  )

# 6. Display final plot
plot(finalPlot_with_labels)

ggsave(
  filename = file.path(plotFolder, paste0("sup_BETvsFCETeconomicallyViableActivity.pdf")),
  plot     = finalPlot_with_labels,
  device   = cairo_pdf,
  width    = 4.5,          # in inches ≈ 180 mm / 25.4
  height   = 5.5,          # in inches (adjust aspect ratio as appropriate)
  units    = "in",
  dpi      = 300           # ensures minimum resolution for any raster elements
)
```

## Suppplementary Fig: Feasibility plot for veh share
```{r, fig.width= 5, fig.height= 8.5, fig.fullwidth=FALSE}
TCOdata <- loadTCO(dataFolder)
binnedWeightedMileage <- prepareMileageData(dataFolder, bin = TRUE, reduce = FALSE)
reducedBinnedWeightedMileage <- prepareMileageData(dataFolder, bin = TRUE, reduce = TRUE)
ranges <- loadRanges(dataFolder)
infrastructure <- loadInfrastructureBuildUp(dataFolder)
dco <- getDCO(DCOscenarios, TCOdata)
setnames(reducedBinnedWeightedMileage, "binMean", "annualM")
DCOmilageDistribution <- applyMileage(reducedBinnedWeightedMileage, dco)
DCOmilageDistributionShares <- calculateFreightActivityShares(DCOmilageDistribution, focus = "EUR")
feasDCO <- checkFeasMileageDistribution(DCOmilageDistribution, binnedWeightedMileage, reducedBinnedWeightedMileage, ranges, infrastructure, focus = "EUR")


paperScenario <- "Current policies"
DCOscen <- "Medium"
FeasTCOxAnnualMileage1 <- amDistributionBarPlot(feasDCO[DCOscenario == DCOscen], yr = 2030, paperScenario, xAxis = "vehicles", feas = TRUE)
FeasTCOxAnnualMileage2 <- amDistributionBarPlot(feasDCO[DCOscenario == DCOscen], yr = 2035, paperScenario, xAxis = "vehicles", feas = TRUE)

legend <- get_legend(
  FeasTCOxAnnualMileage1 +
    theme(
      legend.position = "bottom",
      legend.justification = "left",   # start from left in its own box
      legend.box.just = "left"
    )
)

# 2. Remove legends from the plots
FeasTCOxAnnualMileage1_noleg <- FeasTCOxAnnualMileage1 + theme(legend.position = "none")
FeasTCOxAnnualMileage2_noleg <- FeasTCOxAnnualMileage2 + theme(legend.position = "none")

# 3. Combine the plots side by side
combined <- plot_grid(
  FeasTCOxAnnualMileage1_noleg,
  FeasTCOxAnnualMileage2_noleg,
  ncol = 2,
  rel_widths = c(1, 1),
  align = "h",
  labels = c("a", "b"),
  label_size = baseTextSize,
  label_fontface = "bold",
  label_x = 0.02,
  label_y = 1.02,
  hjust = 0, vjust = 1
) +
  theme(plot.margin = margin(t = 12, r = 5, b = 5, l = 12))

# 4. Shift legend slightly to the right using a spacer
legend_shifted <- plot_grid(
  NULL,      # empty spacer
  legend,
  ncol = 2,
  rel_widths = c(0.05, 0.3)  # First number: empty space on the left.Second number:space the legend occupies.
)

# 5. Combine plots and shifted legend vertically
finalPlot <- plot_grid(
  combined,
  legend_shifted,
  ncol = 1,
  rel_heights = c(1, 0.08)  
)
finalPlot_with_labels <- ggdraw(finalPlot) +
  draw_label(
    DCOscen, x = 0.02, y = 0.45, angle = 90,
    fontface = "bold",
    fontfamily = "sans",
    size = baseTextSize * 1.2,
    hjust = 0
  ) 


# 6. Display final plot
plot(finalPlot_with_labels)

ggsave(
  filename = file.path(plotFolder, paste0("Sup_FeasibleEconomicallyViableVehShare.pdf")),
  plot     = finalPlot_with_labels,
  device   = cairo_pdf,
  width    = 4.5,          # in inches ≈ 180 mm / 25.4
  height   = 6.2/3,          # in inches (adjust aspect ratio as appropriate)
  units    = "in",
  dpi      = 300           # ensures minimum resolution for any raster elements
)


```


# CAPEX overview 
```{r, fig.width=45, fig.height=10, fig.fullwidth=FALSE}
# Select plot data
yrs <- c(2030)
vehSize <- "Tractor-trailer"
overviewTechs <- c("ICET", "FCET", "BET large battery", "BET small battery")
paperScenario <- 	"Current policies"

salesPrices <- aggregateCountryData(loadSalesPrices(dataFolder), weightType = "stock")[period %in% yrs & truckTechnology %in% overviewTechs & truckClass %in% vehSize & paperScen == paperScenario] 
# Choose BET battery costs for visualisation (equal for all BETs, different for FCETs)
batteryAndFCPrices <- aggregateCountryData(loadBatteryAndFCPrices(dataFolder), weightType = "stock")
batteryAndFCPrices <- unique(batteryAndFCPrices[, c("truckClass", "category", "paperScen", "country") := NULL])  
```
## sales Prices
```{r, fig.width=15, fig.height=10, fig.fullwidth=FALSE}
salesPricedata <- copy(salesPrices)
salesPricedata[truckTechnology == "BET large battery", truckTechnology := "BET\nlarge\nbattery"]
salesPricedata[truckTechnology == "BET small battery", truckTechnology := "BET\nsmall\nbattery"]
salesPricedata[, truckTechnology := factor(truckTechnology, levels = c("ICET", "FCET", "BET\nlarge\nbattery", "BET\nsmall\nbattery"))]
salesPricedata[, vehicleParameterScenario := factor(vehicleParameterScenario, levels = c("LC_HTM", "MC_MTM", "HC_LTM"))]
salesPricedata[parameter == "Fuel cell system", parameter := "Fuel cell\nsystem"]
salesPricedata[parameter == "Vehicle body\nincl. engine", parameter := "Vehicle\nbody incl.\nengine"]
salesPricedata[, parameter := factor(parameter, levels = c("H2 tank", "Fuel cell\nsystem", "Battery", "Vehicle\nbody incl.\nengine"))]

# Stacked Bar Plot
salesPbarPlots <- ggplot(salesPricedata, aes(x = vehicleParameterScenario)) +
  geom_bar(aes(y = value, fill = parameter), position = "stack", stat = "identity", width = 0.8) +
  scale_fill_manual(values = paperColors) + 
  facet_wrap(~ truckTechnology, nrow = 1) +
  labs(x = "", y = paste0("Purchase price [EUR2020]"), title = paste0(vehSize, "\n(", yrs, ")")) +
  scale_x_discrete(labels = function(x) { sub("\\s", "\n", x) }, expand = expansion(mult = c(0.3, 0.3))) +
  scale_y_continuous(labels = function(x) paste0(x/1000, "k")) +
  themePanel +
    theme(
      panel.grid.major.x = element_blank(),
      panel.grid.minor.x = element_blank(),
      panel.grid.major.y = element_line(color = "grey90", linewidth = 1.6 * baseLineWidth),
      panel.grid.minor.y = element_line(color = "grey95", linewidth = 0.5 * baseLineWidth),
      panel.spacing = unit(0.2, "lines"),                 # Slightly more room between facets
      panel.border = element_rect(color = "grey85", fill = NA, linewidth = 0.4),  # Light border
      axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
      legend.position = "right",
      legend.box.just = "left",  
      legend.box = "horizontal",
      legend.direction = "vertical", 
      legend.title = element_text(hjust = 0.5))
```
## Battery and fuel Cell System prices
```{r, fig.width=4.5, fig.height=2.5, fig.fullwidth=FALSE}
rawBatFCPrices_wide <- dcast(
  batteryAndFCPrices[period > 2025], 
  period + parameter + unit + truckTechnology ~ vehicleParameterScenario, 
  value.var = "value"
)

rawBatFCPrices_wide[, LC_HTM := as.numeric(LC_HTM)]
rawBatFCPrices_wide[, HC_LTM := as.numeric(HC_LTM)]
rawBatFCPrices_wide[, MC_MTM := as.numeric(MC_MTM)]

FCPrices <- ggplot(
  rawBatFCPrices_wide[parameter == "Fuel cell system costs"], 
  aes()) +
  geom_ribbon(
    aes(
      x = period,
      ymin = LC_HTM,
      ymax = HC_LTM,
      fill = parameter
    ),
    alpha = 0.5 ) +
  geom_line(
    aes(x = period, y = MC_MTM, color = parameter), size = baseLineWidth
  ) +
  scale_fill_manual(values = paperColors, guide = "none") +
  scale_color_manual(values = paperColors, guide = "none") +
  scale_x_continuous(breaks = seq(2030, 2050, 10), expand = c(0, 0)) +
  scale_y_continuous(limits = c(0, 230),breaks = seq(0, 230, 50), expand = c(0, 0))+
  labs(x = "Year", y = "Cost [EUR2020/kW]", title = "Fuell cell\nsystem") +
  themePanel +
    theme(
      panel.grid.major.x = element_blank(),
      panel.grid.minor.x = element_blank(),
      panel.grid.major.y = element_line(color = "grey90", linewidth = 1.6 * baseLineWidth),
      panel.grid.minor.y = element_line(color = "grey95", linewidth = 0.5 * baseLineWidth)
    )  

BatPrices <- ggplot(
  rawBatFCPrices_wide[period > 2025 & parameter == "Battery costs" & truckTechnology == "BET large battery"], 
  aes()) +
  geom_ribbon(
    aes(
      x = period,
      ymin = LC_HTM,
      ymax = HC_LTM,
      fill = parameter,
    ),
    alpha = 0.5 ) +
  geom_line(
    aes(x = period, y = MC_MTM, color = parameter), size = baseLineWidth
  ) +
  scale_fill_manual(values = paperColors, guide = "none") +
  scale_color_manual(values = paperColors, guide = "none") +
  scale_x_continuous(breaks = seq(2030, 2050, 10), expand = c(0, 0)) +
  scale_y_continuous(limits = c(0, 230),breaks = seq(0, 230, 50), expand = c(0, 0))+
  labs(x = "Year", y = "Costs [EUR2020/kWh]", title = "Battery\nsystem" )+
  themePanel +
    theme(
      panel.grid.major.x = element_blank(),
      panel.grid.minor.x = element_blank(),
      panel.grid.major.y = element_line(color = "grey90", linewidth = 1.6 * baseLineWidth),
      panel.grid.minor.y = element_line(color = "grey95", linewidth = 0.5 * baseLineWidth)
    ) 

combined_plotCAPEX <- (
  (BatPrices | FCPrices | salesPbarPlots)) +
    plot_layout(widths = c(0.26, 0.26, 1)) + 
  plot_annotation(tag_levels = "a") &
    theme(
      plot.tag = element_text(size = baseTextSize*1.2, face = "bold")  # adjust size here
    )

plot(combined_plotCAPEX)

ggsave(
  file.path(plotFolder, "Sup_pricesPanelCAPEX.pdf"),
  plot     = combined_plotCAPEX,
  device   = cairo_pdf,
  width    = 4.5,          # in inches ≈ 180 mm / 25.4
  height   = 2.5,          # in inches (adjust aspect ratio as appropriate)
  units    = "in",
  dpi      = 300           # ensures minimum resolution for any raster elements
)

```

# OPEX panel
## energy carrier prices enduse vs wholesale 
```{r, fig.width=4.5/2, fig.height=6/3, fig.fullwidth=FALSE}

fuelPrices <- aggregateCountryData(loadFuelPrices(dataFolder), weightType = "stock")[period > 2025 & paperScen == "Current policies"]

enduseFuelPrices <- fuelPrices[, .(value = sum(value)), by = c("energyCarrierParameterScenario", "period", "country", "unit", "energyCarrier", "paperScen")]
enduseFuelPrices[, parameter := "Enduse"]
data <- fuelPrices[parameter == "Wholesale"]
data <- rbind(data, enduseFuelPrices)

fuelsWide <- dcast(
  data, 
  period + energyCarrier + parameter + unit + paperScen + country ~ energyCarrierParameterScenario, 
  value.var = "value"
)
fuelsWide <- fuelsWide[!energyCarrier == "Mixed Charging"]
fuelsWide[, energyCarrier := factor(energyCarrier, levels = c("Hydrogen", "CCS", "MCS", "Diesel mix", "Diesel fossil", "Diesel bio", "Diesel syn"))]

HydrogenPrices <- ggplot(
  fuelsWide[energyCarrier == "Hydrogen" & parameter %in% c("Wholesale", "Enduse")], 
  aes()) +
  geom_ribbon_pattern(
    aes(
      x = period,
      ymin = PROG,
      ymax = BAU,
      fill = energyCarrier,
      pattern = parameter
    ),
    alpha = 0.2,
    pattern_density = 0.2,
   pattern_spacing = 0.05,
   pattern_size = 0.1) +
  scale_pattern_manual(
  values = c(
    "Wholesale" = "circle",
    "Enduse" = "stripe")) +
  scale_fill_manual(values = paperColors) +
  coord_cartesian(ylim = c(0, 0.3)) +
  scale_x_continuous(breaks = seq(2030, 2050, 10), expand = c(0, 0)) +
  labs(x = "Year", y = "Hydrogen [EUR2020/kWh]", title = "Wholesale vs.\nenduse", fill = "") +
    guides(
    fill = guide_legend(override.aes = list(pattern = "none")),
    pattern = guide_legend(title = "parameter")
  ) +
  themePanel+
  theme(
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    panel.grid.major.y = element_line(color = "grey90", linewidth = 1.6 * baseLineWidth),
    panel.grid.minor.y = element_line(color = "grey95", linewidth = 0.5 * baseLineWidth)
  )


ElecPrices <- ggplot(
  fuelsWide[energyCarrier %in% c("MCS", "CCS") & parameter %in% c("Wholesale", "Enduse")], 
  aes()) +
  geom_ribbon_pattern(
    aes(
      x = period,
      ymin = PROG,
      ymax = BAU,
      fill = energyCarrier,
      pattern = parameter
      ),
      alpha = 0.5,
      pattern_density = 0.2,
   pattern_spacing = 0.05,
   pattern_size = 0.1) +
  scale_fill_manual(values = paperColors) +
  coord_cartesian(ylim = c(0, 0.45)) +
  scale_x_continuous(breaks = seq(2030, 2050, 10), expand = c(0, 0)) +
  labs(x = "Year", y = "Electricity [EUR2020/kWh]", title = "Wholesale vs.\nenduse", fill = "") +
    guides(
    fill = guide_legend(override.aes = list(pattern = "none")),
    pattern = guide_legend(title = "parameter")
  ) +
  themePanel+
  theme(
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    panel.grid.major.y = element_line(color = "grey90", linewidth = 1.6 * baseLineWidth),
    panel.grid.minor.y = element_line(color = "grey95", linewidth = 0.5 * baseLineWidth)
  )


fuelsWide[energyCarrier == "Diesel bio", energyCarrier := "Bio"]
fuelsWide[energyCarrier == "Diesel syn", energyCarrier := "Syn"]
fuelsWide[energyCarrier == "Diesel fossil", energyCarrier := "Fossil"]
fuelsWide[energyCarrier == "Diesel mix", energyCarrier := "Mix"]
fuelsWide[, energyCarrier := factor(energyCarrier, levels = c("Fossil", "Bio", "Syn", "Mix"))]

DieselPrices <- ggplot() +
  geom_ribbon_pattern(
    data = fuelsWide[
      (energyCarrier %in% c("Bio", "Syn", "Fossil") & parameter == "Wholesale") |
        (energyCarrier == "Mix" & parameter == "Enduse")
    ],
    aes(
      x = period,
      ymin = PROG,  # backticks if name has spaces
      ymax = BAU,
      fill = energyCarrier,
      pattern = parameter
    ),
    alpha = 0.5,
    pattern_density = 0.2,
   pattern_spacing = 0.05,
   pattern_size = 0.1) +
  scale_fill_manual(values = paperColors) +
  geom_line(
    data = fuelsWide[energyCarrier == "Fossil" & parameter == "Wholesale"],
    aes(x = period, y = BAU),
    color = "black"
  ) +
  geom_point(
    data = fuelsWide[energyCarrier == "Fossil" & parameter == "Wholesale"],
    aes(x = period, y = BAU),
    shape = 1,        # solid circle
    size = 0.5,        # small dot
    color = "black"
  ) +
  coord_cartesian(ylim = c(0, 0.3)) +
  scale_x_continuous(breaks = seq(2030, 2050, 10), expand = c(0, 0)) +
  labs(x = "Year", y = "Diesel [EUR2020/kWh]", title = "Wholesale vs.\nenduse", fill = "") +
    guides(
    fill = guide_legend(override.aes = list(pattern = "none")),
    pattern = guide_legend(title = "parameter")
  ) +
  themePanel +
  theme(
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    panel.grid.major.y = element_line(color = "grey90", linewidth = 1.6 * baseLineWidth),
    panel.grid.minor.y = element_line(color = "grey95", linewidth = 0.5 * baseLineWidth)
  )



plot(HydrogenPrices)
plot(ElecPrices)
plot(DieselPrices)
```
## energy carrier prices enduse stacked bar plots
```{r, fig.width=3, fig.height=6/3, fig.fullwidth=FALSE}

# Hydrogen
rose5 <- c(
  "#F7C7CC",  # light rose (brighter, clearer)
  "#EC8FA1",  # rose pink (higher saturation)
  "#D35A78",  # strong rose (in-between mid-tone)
  "#B73155",  # deep saturated raspberry
  "#731936"   # dark wine rose (strong contrast)
)
hydrogen <- fuelPrices[energyCarrier == "Hydrogen" & period == 2030]
hydrogen[parameter == "Station Overhead, Profit and Mark-Up", parameter := "Station overhead,\nprofit and mark-up"]
hydrogen[parameter == "Taxes, Fees, Levies and charges", parameter := "Taxes, fees, levies,\nand charges"]
hydrogen[parameter == "Transport and distribution", parameter := "Transport and\ndistribution"]
hydrogen[, parameter := factor(parameter, levels = c("Taxes, fees, levies,\nand charges", "Station overhead,\nprofit and mark-up", "Station", "Transport and\ndistribution", "Wholesale"))]
hydrogenBarPlots <- ggplot(hydrogen, aes(x = `energyCarrierParameterScenario`)) +
  geom_bar(aes(y = value, fill = parameter), position = "stack", stat = "identity", width = 0.8) +
 scale_fill_manual(values = rose5) + 
  labs(x = "", y = "Hydrogen [EUR2020/kWh]", title = "Hydrogen: Enduse price\ncomponents (2030)", fill = "") +
  scale_x_discrete(labels = function(x) { sub("\\s", "\n", x) }, expand = expansion(mult = c(0.3, 0.3))) +
  themePanel +
  theme(
    panel.spacing = unit(0.2, "lines"), # More room between facets
    panel.border = element_rect(color = "grey85", fill = NA, linewidth = 0.5 * baseLineWidth),  # Light border
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    panel.grid.major.y = element_line(color = "grey90", linewidth = 1.6 * baseLineWidth),
    panel.grid.minor.y = element_line(color = "grey95", linewidth = 0.5 * baseLineWidth)
  )

plot(hydrogenBarPlots)

# Electricity
electricity <- fuelPrices[energyCarrier %in% c("MCS", "CCS", "Mixed Charging") & period == 2030]
purple7 <- c(
  "#ECE7F3",  # soft lavender
  "#D2C4E6",  # muted light purple
  "#B89ED8",  # dusty purple
  "#9C78CA",  # mid muted purple
  "#7E53B7",  # rich muted purple
  "#5A3192",  # deep desaturated purple
  "#381B66"   # dark eggplant
)
electricity[parameter %in% c("Network Costs", 
                      "Network fees savings potential"), parameter := "General network\ncosts"]
electricity[parameter %in% c("Taxes, Fees, Levies and charges - MCS",
                      "Taxes, Fees, Levies and charges - Depot"), parameter := "Taxes, fees, levies,\nand charges"]
electricity[parameter == "Station Overhead, Profit and Mark-Up", parameter := "Station overhead,\nprofit and mark-up"]
electricity[energyCarrier == "Mixed Charging", energyCarrier := "Mixed"]
# Sum up for "General network costs"
electricity <- electricity[, .(value = sum(value)), by = c("energyCarrierParameterScenario", "period", "country", "unit", "energyCarrier", "paperScen", "parameter")]
electricity[, parameter := factor(parameter, levels = c("Taxes, fees, levies,\nand charges", "Station overhead,\nprofit and mark-up", "Grid extension", "Station", "General network\ncosts", "Wholesale"))]
electricityBarPlots <- ggplot(electricity, aes(x = `energyCarrierParameterScenario`)) +
  geom_bar(aes(y = value, fill = parameter), position = "stack", stat = "identity", width = 0.8) +
 scale_fill_manual(values = purple7) + 
  facet_wrap(~ energyCarrier, nrow = 1) +
  labs(x = "", y = "Electricity [EUR2020/kWh]", title = "Electricity: Enduse price\ncomponents (2030)", fill = "") +
  scale_x_discrete(labels = function(x) { sub("\\s", "\n", x) }, expand = expansion(mult = c(0.3, 0.3))) +
  themePanel +
  theme(
    panel.spacing = unit(0.2, "lines"), # More room between facets
    panel.border = element_rect(color = "grey85", fill = NA, linewidth = 0.5 * baseLineWidth),  # Light border
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    panel.grid.major.y = element_line(color = "grey90", linewidth = 1.6 * baseLineWidth),
    panel.grid.minor.y = element_line(color = "grey95", linewidth = 0.5 * baseLineWidth)
  )

plot(electricityBarPlots)

# Diesel
diesel <- fuelPrices[energyCarrier %in% c("Diesel bio", "Diesel syn", "Diesel fossil", "Diesel mix") & period == 2030]
green4 <- c(
  "#E0F5E0",  # bright mint
  "#7BCB82",  # vivid green
  "#21843E",  # strong deep green
  "#00381A"   # near-black forest green
)
diesel[parameter == "Excise Duty", parameter := "Excise\nduty"]
diesel[parameter == "Total Diesel Mark-Up", parameter := "Total\nmarkup"]
diesel[, parameter := factor(parameter, levels = c("CO2 tax", "Excise\nduty", "Total\nmarkup", "Transport and distribution", "Wholesale"))]
diesel[energyCarrier == "Diesel bio", energyCarrier := "Bio"]
diesel[energyCarrier == "Diesel syn", energyCarrier := "Syn"]
diesel[energyCarrier == "Diesel fossil", energyCarrier := "Fossil"]
diesel[energyCarrier == "Diesel mix", energyCarrier := "Mix"]
diesel[, energyCarrier := factor(energyCarrier, levels = c("Fossil", "Bio", "Syn", "Mix"))]

dieselBarPlots <- ggplot(diesel, aes(x = `energyCarrierParameterScenario`)) +
  geom_bar(aes(y = value, fill = parameter), position = "stack", stat = "identity", width = 0.8) +
 scale_fill_manual(values = green4) + 
  facet_wrap(~ energyCarrier, nrow = 1) +
  labs(x = "", y = "Diesel [EUR2020/kWh]", title = "Diesel: Enduse price\ncomponents (2030)", fill = "") +
  scale_x_discrete(labels = function(x) { sub("\\s", "\n", x) }, expand = expansion(mult = c(0.3, 0.3))) +
  themePanel +
  theme(
    panel.spacing = unit(0.2, "lines"), # More room between facets
    panel.border = element_rect(color = "grey85", fill = NA, linewidth = 0.5 * baseLineWidth),  # Light border
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    panel.grid.major.y = element_line(color = "grey90", linewidth = 1.6 * baseLineWidth),
    panel.grid.minor.y = element_line(color = "grey95", linewidth = 0.5 * baseLineWidth)
  )



plot(dieselBarPlots)
```
##  panel
```{r, fig.width=4.5, fig.height=6, fig.fullwidth=FALSE}


col1 <- (hydrogenBarPlots | HydrogenPrices) + plot_layout(widths = c(1.1, 0.8))
col2 <- (electricityBarPlots | ElecPrices) + plot_layout(widths = c(1.1, 0.8))
col3 <- (dieselBarPlots | DieselPrices) + plot_layout(widths = c(1.1, 0.5))

combined_plotSupplementary <- (
  col1/
  col2/
  col3
) + plot_annotation(tag_levels = "a") &
  theme(plot.tag = element_text(size = baseTextSize * 1.2, face = "bold"))
plot(combined_plotSupplementary)

ggsave(
  file.path(plotFolder, "Sup_pricesPanelFuel.pdf"),
  plot = combined_plotSupplementary,
  device   = cairo_pdf,
  width    = 4.5,          # in inches ≈ 180 mm / 25.4
  height   = 6,          # in inches (adjust aspect ratio as appropriate)
  units    = "in",
  dpi      = 400           # ensures minimum resolution for any raster elements
)


```

```{r, fig.width=4.5, fig.height=1.5, fig.fullwidth=FALSE}
dieselBlendShares <- loadDieselBlendShares(dataFolder)[, value := as.numeric(value) * 100]
dieselBlendShares <- aggregateCountryData(dieselBlendShares, weightType = "stock")[paperScen == "Current policies"]
dieselBlendShares <- unique(dieselBlendShares[, c("period", "parameter", "value", "energyCarrierParameterScenario")]) 
fossil <- dieselBlendShares[, .(value = sum(value)), by = c("period", "energyCarrierParameterScenario")]
fossil[, value := round(100 - as.numeric(value))][, parameter := "Fossil diesel"]
dieselBlendShares <- rbind(dieselBlendShares, fossil)
dieselBlendShares[parameter == "Share Biodiesel", parameter := "Biodiesel"]
dieselBlendShares[parameter == "Share Synthetic Diesel (E-Fuels)", parameter := "Synthetic Diesel (E-Fuels)"]
colors <- c(
  "#7BCB82",  # vivid green
  "lightgrey",  # bright mint
  "#FFCC00"  # strong deep green
)


blendShares <- ggplot(dieselBlendShares[period < 2045], aes(x = period, y = value, fill = parameter)) +
  geom_area(position = "stack", size = 0, alpha = 0.8) +
  scale_fill_manual(values = colors) + 
  facet_wrap(~ energyCarrierParameterScenario) +
  labs(
    x = "Period",
    y = "Share [%]",
    fill = ""
  ) +
  scale_y_continuous(breaks = seq(0, 100, 25), expand = c(0, 0)) +
  scale_x_continuous(breaks = seq(2030, 2040, 5), expand = c(0, 0)) +
  themePanel +
  theme(
    panel.spacing = unit(1, "lines"), # More room between facets
    panel.border = element_rect(color = "grey85", fill = NA, linewidth = 0.5 * baseLineWidth),  # Light border
  )

plot(blendShares)


ggsave(
  file.path(plotFolder, "Sup_DieselBlendShares.pdf"),
  plot = blendShares,
  device   = cairo_pdf,
  width    = 4.5,          # in inches ≈ 180 mm / 25.4
  height   = 1.5,          # in inches (adjust aspect ratio as appropriate)
  units    = "in",
  dpi      = 400           # ensures minimum resolution for any raster elements
)


```

```{r, fig.width=3, fig.height=1.5, fig.fullwidth=FALSE}
infrastructure <- loadInfrastructureBuildUp(dataFolder)

infraPlot <- ggplot(data = infrastructure, aes(x = period, y = value * 100)) +
  geom_line(linewidth = baseLineWidth) +
  labs(x = "Year", y = "Fast-charging\ninfrastructure\navailability [%]") +
  scale_x_continuous(limits = c(2025, 2051), expand = expansion(mult = c(0, 0)), breaks = c(2030, 2035, 2040, 2045, 2050)) +
  themePanel +
    theme(
      panel.grid.major.x = element_blank(),
      panel.grid.minor.x = element_blank(),
      panel.grid.major.y = element_line(color = "grey90", linewidth = 1.6 * baseLineWidth),
      panel.grid.minor.y = element_line(color = "grey95", linewidth = 0.5 * baseLineWidth)
    ) 

plot(infraPlot)

ggsave(
  file.path(plotFolder, "Sup_infraPlot.pdf"),
  plot = infraPlot,
  device   = cairo_pdf,
  width    = 3,          # in inches ≈ 180 mm / 25.4
  height   = 1.5,          # in inches (adjust aspect ratio as appropriate)
  units    = "in",
  dpi      = 400           # ensures minimum resolution for any raster elements
)


```
